### ISSUE TITLE
flixtraktor  | Error: Invalid or corrupt jarfile /opt/flixtraktor/flixtraktor.jar

### ISSUE THREAD

**Issue by chrisb86** [dylanvdbrink/FlixTraktor#6]
I try to build the image because the Docker hub repo is empty.

When I try to run flixtraktor it shows the error "flixtraktor  | Error: Invalid or corrupt jarfile /opt/flixtraktor/flixtraktor.jar".

My compose.yml:

```
version: "3"
services:
  flixtraktor:
    image: flixtraktor
    # image: dylanvdbrink/flixtraktor:latest
    container_name: flixtraktor
    restart: unless-stopped
    build:
      context: https://github.com/dylanvdbrink/FlixTraktor.git
```
